export interface FoodItem {
  name: string;
  Breakfast: number;
  Lunch: number;
  Dinner: number;
  Diabetes: number;
  LactoseIntolerant: number;
  Thyroid: number;
  VegNonVeg: number;
  Category: string;
  calories: number;
  serving_size_g: number;
  fat_total_g: number;
  fat_saturated_g: number;
  cholesterol_mg: number;
  sodium_mg: number;
  carbohydrates_total_g: number;
  fiber_g: number;
  sugar_g: number;
  protein_g: number;
}

export interface Meals {
  Breakfast: Record<string, FoodItem[]>;
  Lunch: Record<string, FoodItem[]>;
  Dinner: Record<string, FoodItem[]>;
}

export const foodData: FoodItem[] = [
  {
    name: "rajma",
    Breakfast: 1,
    Lunch: 1,
    Dinner: 0,
    Diabetes: 1,
    LactoseIntolerant: 1,
    Thyroid: 0,
    VegNonVeg: 0,
    Category: "protein",
    calories: 98.5,
    serving_size_g: 100,
    fat_total_g: 2.6,
    fat_saturated_g: 0.6,
    cholesterol_mg: 1,
    sodium_mg: 228,
    carbohydrates_total_g: 15.1,
    fiber_g: 3.7,
    sugar_g: 3.1,
    protein_g: 5.3,
  },
  {
    name: "vegetable stew",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 1,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "vegetable",
    calories: 32.9,
    serving_size_g: 100,
    fat_total_g: 0.8,
    fat_saturated_g: 0.2,
    cholesterol_mg: 0,
    sodium_mg: 251,
    carbohydrates_total_g: 5.4,
    fiber_g: 0.7,
    sugar_g: 0.8,
    protein_g: 1.2,
  },
  {
    name: "chana masala",
    Breakfast: 1,
    Lunch: 1,
    Dinner: 1,
    Diabetes: 1,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "protein",
    calories: 146.6,
    serving_size_g: 100,
    fat_total_g: 8.6,
    fat_saturated_g: 1.1,
    cholesterol_mg: 0,
    sodium_mg: 120,
    carbohydrates_total_g: 14.7,
    fiber_g: 3.9,
    sugar_g: 3.6,
    protein_g: 3.9,
  },
  {
    name: "chapati",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 1,
    Diabetes: 0,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "bread",
    calories: 149.15,
    serving_size_g: 50,
    fat_total_g: 4.71,
    fat_saturated_g: 1.65,
    cholesterol_mg: 0,
    sodium_mg: 151,
    carbohydrates_total_g: 23,
    fiber_g: 4.85,
    sugar_g: 1.45,
    protein_g: 3.91,
  },
  {
    name: "idli",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 0,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "grains",
    calories: 153.9,
    serving_size_g: 100,
    fat_total_g: 1.1,
    fat_saturated_g: 0.2,
    cholesterol_mg: 0,
    sodium_mg: 195,
    carbohydrates_total_g: 29.6,
    fiber_g: 1.4,
    sugar_g: 0.3,
    protein_g: 4.3,
  },
  {
    name: "smoothie",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 0,
    LactoseIntolerant: 0,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "beverages",
    calories: 79.7,
    serving_size_g: 100,
    fat_total_g: 0.8,
    fat_saturated_g: 0.5,
    cholesterol_mg: 2,
    sodium_mg: 29,
    carbohydrates_total_g: 16.7,
    fiber_g: 1.4,
    sugar_g: 11.7,
    protein_g: 2.7,
  },
  {
    name: "paneer butter masala",
    Breakfast: 0,
    Lunch: 1,
    Dinner: 1,
    Diabetes: 0,
    LactoseIntolerant: 0,
    Thyroid: 0,
    VegNonVeg: 0,
    Category: "Dairy",
    calories: 101.8,
    serving_size_g: 100,
    fat_total_g: 8.1,
    fat_saturated_g: 4.3,
    cholesterol_mg: 20,
    sodium_mg: 258,
    carbohydrates_total_g: 3.5,
    fiber_g: 0.8,
    sugar_g: 1.8,
    protein_g: 4.2,
  },
  {
    name: "raita",
    Breakfast: 1,
    Lunch: 1,
    Dinner: 1,
    Diabetes: 1,
    LactoseIntolerant: 0,
    Thyroid: 0,
    VegNonVeg: 0,
    Category: "protein",
    calories: 45.6,
    serving_size_g: 100,
    fat_total_g: 2.4,
    fat_saturated_g: 1.5,
    cholesterol_mg: 8,
    sodium_mg: 33,
    carbohydrates_total_g: 4.1,
    fiber_g: 0.4,
    sugar_g: 3.6,
    protein_g: 2.7,
  },
  {
    name: "bharta",
    Breakfast: 1,
    Lunch: 1,
    Dinner: 1,
    Diabetes: 1,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "vegetable",
    calories: 49.8,
    serving_size_g: 100,
    fat_total_g: 2.4,
    fat_saturated_g: 0.2,
    cholesterol_mg: 0,
    sodium_mg: 152,
    carbohydrates_total_g: 7.5,
    fiber_g: 2.1,
    sugar_g: 3,
    protein_g: 0.9,
  },
  {
    name: "buttermilk",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 0,
    LactoseIntolerant: 0,
    Thyroid: 0,
    VegNonVeg: 0,
    Category: "Dairy",
    calories: 40.2,
    serving_size_g: 100,
    fat_total_g: 0.9,
    fat_saturated_g: 0.5,
    cholesterol_mg: 4,
    sodium_mg: 187,
    carbohydrates_total_g: 4.8,
    fiber_g: 0,
    sugar_g: 4.8,
    protein_g: 3.3,
  },
  {
    name: "paneer",
    Breakfast: 0,
    Lunch: 1,
    Dinner: 1,
    Diabetes: 1,
    LactoseIntolerant: 0,
    Thyroid: 0,
    VegNonVeg: 0,
    Category: "Dairy",
    calories: 149.85,
    serving_size_g: 50,
    fat_total_g: 12,
    fat_saturated_g: 6.45,
    cholesterol_mg: 35,
    sodium_mg: 375.5,
    carbohydrates_total_g: 3,
    fiber_g: 0,
    sugar_g: 2.3,
    protein_g: 18.2,
  },
  {
    name: "boiled eggs",
    Breakfast: 1,
    Lunch: 1,
    Dinner: 0,
    Diabetes: 1,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 1,
    Category: "non-veg protein",
    calories: 150.6,
    serving_size_g: 100,
    fat_total_g: 10.4,
    fat_saturated_g: 3.3,
    cholesterol_mg: 374,
    sodium_mg: 126,
    carbohydrates_total_g: 1.1,
    fiber_g: 0,
    sugar_g: 1.1,
    protein_g: 12.7,
  },
  {
    name: "aloo gobi",
    Breakfast: 0,
    Lunch: 1,
    Dinner: 1,
    Diabetes: 0,
    LactoseIntolerant: 1,
    Thyroid: 0,
    VegNonVeg: 0,
    Category: "vegetable",
    calories: 70.1,
    serving_size_g: 100,
    fat_total_g: 3.6,
    fat_saturated_g: 0.6,
    cholesterol_mg: 0,
    sodium_mg: 147,
    carbohydrates_total_g: 9.3,
    fiber_g: 1.8,
    sugar_g: 1.1,
    protein_g: 1.6,
  },
  {
    name: "pav bhaji",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 0,
    LactoseIntolerant: 1,
    Thyroid: 0,
    VegNonVeg: 0,
    Category: "bread",
    calories: 98.9,
    serving_size_g: 100,
    fat_total_g: 2.8,
    fat_saturated_g: 1.2,
    cholesterol_mg: 12,
    sodium_mg: 143,
    carbohydrates_total_g: 15.7,
    fiber_g: 2.3,
    sugar_g: 2.6,
    protein_g: 2.9,
  },
  {
    name: "sweet potato fries",
    Breakfast: 0,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 0,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "vegetable",
    calories: 142.3,
    serving_size_g: 50,
    fat_total_g: 10.1,
    fat_saturated_g: 0.8,
    cholesterol_mg: 0,
    sodium_mg: 96.5,
    carbohydrates_total_g: 23.3,
    fiber_g: 3.1,
    sugar_g: 5.8,
    protein_g: 1.5,
  },
  {
    name: "dal fry",
    Breakfast: 0,
    Lunch: 1,
    Dinner: 1,
    Diabetes: 1,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "cereals",
    calories: 90.2,
    serving_size_g: 100,
    fat_total_g: 3.9,
    fat_saturated_g: 0.3,
    cholesterol_mg: 0,
    sodium_mg: 191,
    carbohydrates_total_g: 10.6,
    fiber_g: 3.9,
    sugar_g: 1.8,
    protein_g: 4.1,
  },
  {
    name: "curd rice",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 0,
    LactoseIntolerant: 0,
    Thyroid: 0,
    VegNonVeg: 0,
    Category: "grains",
    calories: 92.4,
    serving_size_g: 100,
    fat_total_g: 1.4,
    fat_saturated_g: 0.9,
    cholesterol_mg: 5,
    sodium_mg: 74,
    carbohydrates_total_g: 16.7,
    fiber_g: 0.2,
    sugar_g: 2,
    protein_g: 2.7,
  },
  {
    name: "vegetable",
    Breakfast: 0,
    Lunch: 1,
    Dinner: 1,
    Diabetes: 1,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "vegetable",
    calories: 32.7,
    serving_size_g: 100,
    fat_total_g: 0.3,
    fat_saturated_g: 0.1,
    cholesterol_mg: 0,
    sodium_mg: 30,
    carbohydrates_total_g: 6.8,
    fiber_g: 3,
    sugar_g: 2.6,
    protein_g: 1.7,
  },
  {
    name: "vegetable salad",
    Breakfast: 0,
    Lunch: 1,
    Dinner: 1,
    Diabetes: 1,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "salad",
    calories: 69.3,
    serving_size_g: 100,
    fat_total_g: 4.1,
    fat_saturated_g: 1,
    cholesterol_mg: 3,
    sodium_mg: 227,
    carbohydrates_total_g: 6.6,
    fiber_g: 1.6,
    sugar_g: 3.3,
    protein_g: 2.3,
  },
  {
    name: "boil dal",
    Breakfast: 0,
    Lunch: 1,
    Dinner: 0,
    Diabetes: 1,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "cereals",
    calories: 102.2,
    serving_size_g: 100,
    fat_total_g: 1.9,
    fat_saturated_g: 0.3,
    cholesterol_mg: 0,
    sodium_mg: 200,
    carbohydrates_total_g: 16,
    fiber_g: 5.9,
    sugar_g: 2.1,
    protein_g: 6.6,
  },
  {
    name: "masala dosa",
    Breakfast: 1,
    Lunch: 1,
    Dinner: 0,
    Diabetes: 0,
    LactoseIntolerant: 1,
    Thyroid: 0,
    VegNonVeg: 0,
    Category: "grains",
    calories: 171.7,
    serving_size_g: 100,
    fat_total_g: 3.8,
    fat_saturated_g: 0.6,
    cholesterol_mg: 0,
    sodium_mg: 98,
    carbohydrates_total_g: 29.7,
    fiber_g: 0.9,
    sugar_g: 0.2,
    protein_g: 4,
  },
  {
    name: "capsicum",
    Breakfast: 0,
    Lunch: 1,
    Dinner: 1,
    Diabetes: 1,
    LactoseIntolerant: 1,
    Thyroid: 0,
    VegNonVeg: 0,
    Category: "vegetable",
    calories: 39.2,
    serving_size_g: 100,
    fat_total_g: 0.2,
    fat_saturated_g: 0,
    cholesterol_mg: 0,
    sodium_mg: 6,
    carbohydrates_total_g: 9.6,
    fiber_g: 1.5,
    sugar_g: 5.2,
    protein_g: 2,
  },
  {
    name: "vegetable biryani",
    Breakfast: 0,
    Lunch: 1,
    Dinner: 1,
    Diabetes: 0,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "protein",
    calories: 118.1,
    serving_size_g: 100,
    fat_total_g: 2.3,
    fat_saturated_g: 0.3,
    cholesterol_mg: 0,
    sodium_mg: 187,
    carbohydrates_total_g: 22.2,
    fiber_g: 1.1,
    sugar_g: 2.1,
    protein_g: 2.5,
  },
  {
    name: "mutton",
    Breakfast: 0,
    Lunch: 1,
    Dinner: 1,
    Diabetes: 1,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 1,
    Category: "non-veg protein",
    calories: 144.8,
    serving_size_g: 50,
    fat_total_g: 10.65,
    fat_saturated_g: 4.45,
    cholesterol_mg: 49,
    sodium_mg: 36,
    carbohydrates_total_g: 0,
    fiber_g: 0,
    sugar_g: 0,
    protein_g: 24.4,
  },
  {
    name: "fish fry",
    Breakfast: 0,
    Lunch: 1,
    Dinner: 1,
    Diabetes: 0,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 1,
    Category: "non-veg protein",
    calories: 130.9,
    serving_size_g: 100,
    fat_total_g: 5,
    fat_saturated_g: 0.6,
    cholesterol_mg: 28,
    sodium_mg: 273,
    carbohydrates_total_g: 13.7,
    fiber_g: 0.9,
    sugar_g: 0.4,
    protein_g: 8.3,
  },
  {
    name: "lemon rice",
    Breakfast: 0,
    Lunch: 1,
    Dinner: 1,
    Diabetes: 0,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "grains",
    calories: 122.2,
    serving_size_g: 100,
    fat_total_g: 1.6,
    fat_saturated_g: 0.8,
    cholesterol_mg: 3,
    sodium_mg: 58,
    carbohydrates_total_g: 23.8,
    fiber_g: 0.1,
    sugar_g: 0.6,
    protein_g: 2.7,
  },
  {
    name: "oats porridge",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 1,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "cereals",
    calories: 91,
    serving_size_g: 100,
    fat_total_g: 2.4,
    fat_saturated_g: 1.2,
    cholesterol_mg: 7,
    sodium_mg: 47,
    carbohydrates_total_g: 12.7,
    fiber_g: 1.2,
    sugar_g: 0.1,
    protein_g: 4.7,
  },
  {
    name: "chole",
    Breakfast: 1,
    Lunch: 1,
    Dinner: 0,
    Diabetes: 1,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "protein",
    calories: 143.8,
    serving_size_g: 100,
    fat_total_g: 8.4,
    fat_saturated_g: 1.1,
    cholesterol_mg: 0,
    sodium_mg: 122,
    carbohydrates_total_g: 14.5,
    fiber_g: 3.9,
    sugar_g: 3.5,
    protein_g: 3.9,
  },
  {
    name: "chicken biryani",
    Breakfast: 0,
    Lunch: 1,
    Dinner: 1,
    Diabetes: 0,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 1,
    Category: "non-veg protein",
    calories: 140.2,
    serving_size_g: 100,
    fat_total_g: 4.6,
    fat_saturated_g: 0.8,
    cholesterol_mg: 23,
    sodium_mg: 202,
    carbohydrates_total_g: 15.3,
    fiber_g: 0.7,
    sugar_g: 1.5,
    protein_g: 9.5,
  },
  {
    name: "sprouts",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 1,
    LactoseIntolerant: 1,
    Thyroid: 0,
    VegNonVeg: 0,
    Category: "salad",
    calories: 23,
    serving_size_g: 100,
    fat_total_g: 0.7,
    fat_saturated_g: 0.1,
    cholesterol_mg: 0,
    sodium_mg: 5,
    carbohydrates_total_g: 2.1,
    fiber_g: 1.9,
    sugar_g: 0.2,
    protein_g: 4,
  },
  {
    name: "curd",
    Breakfast: 1,
    Lunch: 1,
    Dinner: 1,
    Diabetes: 1,
    LactoseIntolerant: 0,
    Thyroid: 0,
    VegNonVeg: 0,
    Category: "Dairy",
    calories: 62.1,
    serving_size_g: 100,
    fat_total_g: 3.2,
    fat_saturated_g: 2.1,
    cholesterol_mg: 12,
    sodium_mg: 46,
    carbohydrates_total_g: 4.6,
    fiber_g: 0,
    sugar_g: 4.6,
    protein_g: 3.5,
  },
  {
    name: "aloo paratha",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 1,
    Diabetes: 0,
    LactoseIntolerant: 1,
    Thyroid: 0,
    VegNonVeg: 0,
    Category: "bread",
    calories: 115.55,
    serving_size_g: 50,
    fat_total_g: 4,
    fat_saturated_g: 1.8,
    cholesterol_mg: 0,
    sodium_mg: 141,
    carbohydrates_total_g: 17.3,
    fiber_g: 3.3,
    sugar_g: 1.6,
    protein_g: 4.7,
  },
  {
    name: "omelette",
    Breakfast: 1,
    Lunch: 1,
    Dinner: 1,
    Diabetes: 1,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 1,
    Category: "non-veg protein",
    calories: 176.7,
    serving_size_g: 100,
    fat_total_g: 14.3,
    fat_saturated_g: 3.3,
    cholesterol_mg: 347,
    sodium_mg: 296,
    carbohydrates_total_g: 0.8,
    fiber_g: 0,
    sugar_g: 0.3,
    protein_g: 11.9,
  },
  {
    name: "appam",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 0,
    LactoseIntolerant: 0,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "grains",
    calories: 203.2,
    serving_size_g: 100,
    fat_total_g: 5.1,
    fat_saturated_g: 4.5,
    cholesterol_mg: 0,
    sodium_mg: 145,
    carbohydrates_total_g: 36.1,
    fiber_g: 1.3,
    sugar_g: 3.6,
    protein_g: 3.2,
  },
  {
    name: "sweet corn",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 0,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "cereals",
    calories: 98.7,
    serving_size_g: 100,
    fat_total_g: 1.5,
    fat_saturated_g: 0.2,
    cholesterol_mg: 0,
    sodium_mg: 0,
    carbohydrates_total_g: 21.3,
    fiber_g: 2.4,
    sugar_g: 4.5,
    protein_g: 3.4,
  },
  {
    name: "grilled cheese sandwich",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 0,
    LactoseIntolerant: 0,
    Thyroid: 0,
    VegNonVeg: 0,
    Category: "sandwich",
    calories: 352,
    serving_size_g: 100,
    fat_total_g: 21.3,
    fat_saturated_g: 12.4,
    cholesterol_mg: 60,
    sodium_mg: 824,
    carbohydrates_total_g: 27.2,
    fiber_g: 1.3,
    sugar_g: 5.2,
    protein_g: 11,
  },
  {
    name: "vada pav",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 0,
    LactoseIntolerant: 0,
    Thyroid: 0,
    VegNonVeg: 0,
    Category: "grains",
    calories: 206.5,
    serving_size_g: 100,
    fat_total_g: 7.4,
    fat_saturated_g: 0.9,
    cholesterol_mg: 14,
    sodium_mg: 164,
    carbohydrates_total_g: 29.8,
    fiber_g: 2.9,
    sugar_g: 2.8,
    protein_g: 5.9,
  },
  {
    name: "paratha",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 1,
    Diabetes: 0,
    LactoseIntolerant: 0,
    Thyroid: 0,
    VegNonVeg: 0,
    Category: "bread",
    calories: 158.85,
    serving_size_g: 50,
    fat_total_g: 6.55,
    fat_saturated_g: 2.9,
    cholesterol_mg: 0,
    sodium_mg: 226,
    carbohydrates_total_g: 23.05,
    fiber_g: 4.8,
    sugar_g: 2.1,
    protein_g: 3.2,
  },
  {
    name: "chicken sandwich",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 0,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 1,
    Category: "sandwich",
    calories: 243.9,
    serving_size_g: 100,
    fat_total_g: 11.2,
    fat_saturated_g: 2.1,
    cholesterol_mg: 35,
    sodium_mg: 767,
    carbohydrates_total_g: 20.9,
    fiber_g: 1.4,
    sugar_g: 3.6,
    protein_g: 16.2,
  },
  {
    name: "chicken curry",
    Breakfast: 0,
    Lunch: 1,
    Dinner: 1,
    Diabetes: 0,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 1,
    Category: "non-veg protein",
    calories: 106.3,
    serving_size_g: 100,
    fat_total_g: 4.6,
    fat_saturated_g: 0.6,
    cholesterol_mg: 31,
    sodium_mg: 30,
    carbohydrates_total_g: 3.2,
    fiber_g: 0.6,
    sugar_g: 0.9,
    protein_g: 12.1,
  },
  {
    name: "plain dosa",
    Breakfast: 1,
    Lunch: 1,
    Dinner: 0,
    Diabetes: 0,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "grains",
    calories: 170.5,
    serving_size_g: 100,
    fat_total_g: 3.8,
    fat_saturated_g: 0.6,
    cholesterol_mg: 0,
    sodium_mg: 97,
    carbohydrates_total_g: 30,
    fiber_g: 0.9,
    sugar_g: 0.2,
    protein_g: 4,
  },
  {
    name: "rice",
    Breakfast: 0,
    Lunch: 1,
    Dinner: 0,
    Diabetes: 0,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "grains",
    calories: 127.4,
    serving_size_g: 100,
    fat_total_g: 0.3,
    fat_saturated_g: 0.1,
    cholesterol_mg: 0,
    sodium_mg: 1,
    carbohydrates_total_g: 28.4,
    fiber_g: 0.4,
    sugar_g: 0.1,
    protein_g: 2.7,
  },
  {
    name: "sambar",
    Breakfast: 1,
    Lunch: 1,
    Dinner: 0,
    Diabetes: 0,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "vegetable",
    calories: 51.3,
    serving_size_g: 100,
    fat_total_g: 0.3,
    fat_saturated_g: 0,
    cholesterol_mg: 0,
    sodium_mg: 79,
    carbohydrates_total_g: 10.5,
    fiber_g: 2.9,
    sugar_g: 3.6,
    protein_g: 2.8,
  },
  {
    name: "sabudana",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 0,
    LactoseIntolerant: 0,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "grains",
    calories: 183.35,
    serving_size_g: 50,
    fat_total_g: 0,
    fat_saturated_g: 0,
    cholesterol_mg: 0,
    sodium_mg: 1,
    carbohydrates_total_g: 43.95,
    fiber_g: 0.45,
    sugar_g: 1.65,
    protein_g: 0.1,
  },
  {
    name: "coconut chutney",
    Breakfast: 1,
    Lunch: 1,
    Dinner: 1,
    Diabetes: 1,
    LactoseIntolerant: 1,
    Thyroid: 0,
    VegNonVeg: 0,
    Category: "chutney",
    calories: 165,
    serving_size_g: 100,
    fat_total_g: 11.6,
    fat_saturated_g: 7.3,
    cholesterol_mg: 0,
    sodium_mg: 401,
    carbohydrates_total_g: 13.1,
    fiber_g: 4.6,
    sugar_g: 5,
    protein_g: 3.4,
  },
  {
    name: "palak paneer",
    Breakfast: 0,
    Lunch: 1,
    Dinner: 1,
    Diabetes: 1,
    LactoseIntolerant: 0,
    Thyroid: 0,
    VegNonVeg: 0,
    Category: "protein",
    calories: 183.3,
    serving_size_g: 100,
    fat_total_g: 15,
    fat_saturated_g: 5.6,
    cholesterol_mg: 28,
    sodium_mg: 436,
    carbohydrates_total_g: 5.1,
    fiber_g: 1.3,
    sugar_g: 2.3,
    protein_g: 7.5,
  },
  {
    name: "vegetable soup",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 1,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "soup",
    calories: 32.3,
    serving_size_g: 100,
    fat_total_g: 0.8,
    fat_saturated_g: 0.2,
    cholesterol_mg: 1,
    sodium_mg: 256,
    carbohydrates_total_g: 5.3,
    fiber_g: 0.7,
    sugar_g: 0.8,
    protein_g: 1.2,
  },
  {
    name: "mixed vegetable",
    Breakfast: 0,
    Lunch: 1,
    Dinner: 1,
    Diabetes: 1,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "vegetable",
    calories: 32,
    serving_size_g: 100,
    fat_total_g: 0.3,
    fat_saturated_g: 0.1,
    cholesterol_mg: 0,
    sodium_mg: 30,
    carbohydrates_total_g: 6.9,
    fiber_g: 3,
    sugar_g: 2.6,
    protein_g: 1.7,
  },
  {
    name: "pongal",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 1,
    LactoseIntolerant: 1,
    Thyroid: 0,
    VegNonVeg: 0,
    Category: "grains",
    calories: 156.4,
    serving_size_g: 100,
    fat_total_g: 3.8,
    fat_saturated_g: 2.1,
    cholesterol_mg: 7,
    sodium_mg: 1,
    carbohydrates_total_g: 26.4,
    fiber_g: 1.9,
    sugar_g: 0.5,
    protein_g: 3.5,
  },
  {
    name: "moong dal",
    Breakfast: 0,
    Lunch: 1,
    Dinner: 1,
    Diabetes: 1,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "cereals",
    calories: 114.1,
    serving_size_g: 100,
    fat_total_g: 1,
    fat_saturated_g: 0.1,
    cholesterol_mg: 0,
    sodium_mg: 226,
    carbohydrates_total_g: 19.8,
    fiber_g: 7.7,
    sugar_g: 2.8,
    protein_g: 7.6,
  },
  {
    name: "poha",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 1,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "grains",
    calories: 113.8,
    serving_size_g: 100,
    fat_total_g: 0.2,
    fat_saturated_g: 0,
    cholesterol_mg: 0,
    sodium_mg: 3,
    carbohydrates_total_g: 24.9,
    fiber_g: 0,
    sugar_g: 0,
    protein_g: 2.1,
  },
  {
    name: "tomato soup",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 1,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "soup",
    calories: 34.3,
    serving_size_g: 100,
    fat_total_g: 0.2,
    fat_saturated_g: 0,
    cholesterol_mg: 0,
    sodium_mg: 187,
    carbohydrates_total_g: 7.6,
    fiber_g: 0.5,
    sugar_g: 4,
    protein_g: 0.7,
  },
  {
    name: "lassi",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 0,
    LactoseIntolerant: 0,
    Thyroid: 0,
    VegNonVeg: 0,
    Category: "beverages",
    calories: 54.4,
    serving_size_g: 100,
    fat_total_g: 0.8,
    fat_saturated_g: 0.5,
    cholesterol_mg: 3,
    sodium_mg: 39,
    carbohydrates_total_g: 8.9,
    fiber_g: 0.1,
    sugar_g: 8.6,
    protein_g: 2.8,
  },
  {
    name: "puri",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 0,
    LactoseIntolerant: 1,
    Thyroid: 0,
    VegNonVeg: 0,
    Category: "bread",
    calories: 330.2,
    serving_size_g: 100,
    fat_total_g: 22.5,
    fat_saturated_g: 1.8,
    cholesterol_mg: 0,
    sodium_mg: 197,
    carbohydrates_total_g: 28.6,
    fiber_g: 4.2,
    sugar_g: 0.2,
    protein_g: 5.2,
  },
  {
    name: "dal",
    Breakfast: 0,
    Lunch: 1,
    Dinner: 1,
    Diabetes: 1,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "cereals",
    calories: 102.2,
    serving_size_g: 100,
    fat_total_g: 1.9,
    fat_saturated_g: 0.3,
    cholesterol_mg: 0,
    sodium_mg: 200,
    carbohydrates_total_g: 16,
    fiber_g: 5.9,
    sugar_g: 2.1,
    protein_g: 6.6,
  },
  {
    name: "peanut butter sandwich",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 0,
    LactoseIntolerant: 1,
    Thyroid: 0,
    VegNonVeg: 0,
    Category: "sandwich",
    calories: 395.8,
    serving_size_g: 100,
    fat_total_g: 21.4,
    fat_saturated_g: 4.1,
    cholesterol_mg: 0,
    sodium_mg: 492,
    carbohydrates_total_g: 39.3,
    fiber_g: 3.9,
    sugar_g: 6,
    protein_g: 13.9,
  },
  {
    name: "paneer tikka",
    Breakfast: 0,
    Lunch: 1,
    Dinner: 1,
    Diabetes: 1,
    LactoseIntolerant: 0,
    Thyroid: 0,
    VegNonVeg: 0,
    Category: "Dairy",
    calories: 100.4,
    serving_size_g: 100,
    fat_total_g: 8.2,
    fat_saturated_g: 4.3,
    cholesterol_mg: 20,
    sodium_mg: 250,
    carbohydrates_total_g: 3.5,
    fiber_g: 0.8,
    sugar_g: 1.8,
    protein_g: 4.2,
  },
  {
    name: "peanut",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 1,
    LactoseIntolerant: 1,
    Thyroid: 0,
    VegNonVeg: 0,
    Category: "protein",
    calories: 578.5,
    serving_size_g: 100,
    fat_total_g: 50.1,
    fat_saturated_g: 7.9,
    cholesterol_mg: 0,
    sodium_mg: 410,
    carbohydrates_total_g: 21,
    fiber_g: 7.9,
    sugar_g: 5,
    protein_g: 24.1,
  },
  {
    name: "fruit salad",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 1,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "salad",
    calories: 58.7,
    serving_size_g: 100,
    fat_total_g: 0.3,
    fat_saturated_g: 0,
    cholesterol_mg: 0,
    sodium_mg: 1,
    carbohydrates_total_g: 15.1,
    fiber_g: 2,
    sugar_g: 10.2,
    protein_g: 0.8,
  },
  {
    name: "scrambled eggs",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 1,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 1,
    Category: "non-veg protein",
    calories: 150.2,
    serving_size_g: 100,
    fat_total_g: 11,
    fat_saturated_g: 3.3,
    cholesterol_mg: 276,
    sodium_mg: 146,
    carbohydrates_total_g: 1.6,
    fiber_g: 0,
    sugar_g: 1.4,
    protein_g: 10.1,
  },
  {
    name: "chicken tikka masala",
    Breakfast: 0,
    Lunch: 1,
    Dinner: 1,
    Diabetes: 0,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 1,
    Category: "non-veg protein",
    calories: 149.9,
    serving_size_g: 100,
    fat_total_g: 9,
    fat_saturated_g: 5.1,
    cholesterol_mg: 70,
    sodium_mg: 879,
    carbohydrates_total_g: 4,
    fiber_g: 0.8,
    sugar_g: 2.4,
    protein_g: 14,
  },
  {
    name: "tomato chutney",
    Breakfast: 0,
    Lunch: 1,
    Dinner: 1,
    Diabetes: 0,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "chutney",
    calories: 72.3,
    serving_size_g: 100,
    fat_total_g: 0.3,
    fat_saturated_g: 0,
    cholesterol_mg: 0,
    sodium_mg: 220,
    carbohydrates_total_g: 17,
    fiber_g: 1,
    sugar_g: 15.2,
    protein_g: 0.7,
  },
  {
    name: "shrimp",
    Breakfast: 0,
    Lunch: 1,
    Dinner: 0,
    Diabetes: 1,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 1,
    Category: "non-veg protein",
    calories: 119,
    serving_size_g: 100,
    fat_total_g: 1.8,
    fat_saturated_g: 0.6,
    cholesterol_mg: 212,
    sodium_mg: 944,
    carbohydrates_total_g: 1.6,
    fiber_g: 0,
    sugar_g: 0,
    protein_g: 22.6,
  },
  {
    name: "fish curry",
    Breakfast: 0,
    Lunch: 1,
    Dinner: 0,
    Diabetes: 1,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 1,
    Category: "non-veg protein",
    calories: 142.6,
    serving_size_g: 100,
    fat_total_g: 7.2,
    fat_saturated_g: 1,
    cholesterol_mg: 52,
    sodium_mg: 353,
    carbohydrates_total_g: 2.9,
    fiber_g: 0.5,
    sugar_g: 1.3,
    protein_g: 17.1,
  },
  {
    name: "egg curry",
    Breakfast: 0,
    Lunch: 1,
    Dinner: 0,
    Diabetes: 0,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 1,
    Category: "non-veg protein",
    calories: 90.9,
    serving_size_g: 100,
    fat_total_g: 5.5,
    fat_saturated_g: 1,
    cholesterol_mg: 84,
    sodium_mg: 31,
    carbohydrates_total_g: 5.8,
    fiber_g: 1.5,
    sugar_g: 2.6,
    protein_g: 4.3,
  },
  {
    name: "popcorn",
    Breakfast: 0,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 0,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "cereals",
    calories: 374.65,
    serving_size_g: 50,
    fat_total_g: 15.35,
    fat_saturated_g: 7.25,
    cholesterol_mg: 0,
    sodium_mg: 384,
    carbohydrates_total_g: 28.5,
    fiber_g: 4.9,
    sugar_g: 0.15,
    protein_g: 4.24,
  },
  {
    name: "upma",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 0,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "grains",
    calories: 84.2,
    serving_size_g: 100,
    fat_total_g: 2.6,
    fat_saturated_g: 0.2,
    cholesterol_mg: 0,
    sodium_mg: 113,
    carbohydrates_total_g: 13.6,
    fiber_g: 1.3,
    sugar_g: 1.7,
    protein_g: 2.2,
  },
  {
    name: "butter chicken",
    Breakfast: 0,
    Lunch: 1,
    Dinner: 1,
    Diabetes: 0,
    LactoseIntolerant: 0,
    Thyroid: 1,
    VegNonVeg: 1,
    Category: "non-veg protein",
    calories: 152,
    serving_size_g: 100,
    fat_total_g: 9.6,
    fat_saturated_g: 4.2,
    cholesterol_mg: 38,
    sodium_mg: 102,
    carbohydrates_total_g: 5.8,
    fiber_g: 0.8,
    sugar_g: 2.8,
    protein_g: 9.7,
  },
  {
    name: "cucumber",
    Breakfast: 1,
    Lunch: 1,
    Dinner: 0,
    Diabetes: 1,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "vegetable",
    calories: 15.3,
    serving_size_g: 100,
    fat_total_g: 0.1,
    fat_saturated_g: 0,
    cholesterol_mg: 0,
    sodium_mg: 1,
    carbohydrates_total_g: 3.7,
    fiber_g: 0.5,
    sugar_g: 1.7,
    protein_g: 0.6,
  },
  {
    name: "pears",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 1,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "fruit",
    calories: 58.7,
    serving_size_g: 100,
    fat_total_g: 0.1,
    fat_saturated_g: 0,
    cholesterol_mg: 0,
    sodium_mg: 1,
    carbohydrates_total_g: 15.2,
    fiber_g: 3.1,
    sugar_g: 9.8,
    protein_g: 0.4,
  },
  {
    name: "cashew nuts",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 0,
    LactoseIntolerant: 1,
    Thyroid: 0,
    VegNonVeg: 0,
    Category: "protein",
    calories: 293.8,
    serving_size_g: 50,
    fat_total_g: 23.3,
    fat_saturated_g: 4.5,
    cholesterol_mg: 0,
    sodium_mg: 326,
    carbohydrates_total_g: 16.34,
    fiber_g: 0.8,
    sugar_g: 2.55,
    protein_g: 7.7,
  },
  {
    name: "chowmein",
    Breakfast: 0,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 0,
    LactoseIntolerant: 1,
    Thyroid: 0,
    VegNonVeg: 0,
    Category: "protein",
    calories: 160.4,
    serving_size_g: 100,
    fat_total_g: 8.2,
    fat_saturated_g: 1.5,
    cholesterol_mg: 32,
    sodium_mg: 312,
    carbohydrates_total_g: 12.1,
    fiber_g: 0.9,
    sugar_g: 1.1,
    protein_g: 10.1,
  },
  {
    name: "grapes",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 0,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "fruit",
    calories: 69.6,
    serving_size_g: 100,
    fat_total_g: 0.2,
    fat_saturated_g: 0.1,
    cholesterol_mg: 0,
    sodium_mg: 2,
    carbohydrates_total_g: 18.1,
    fiber_g: 0.9,
    sugar_g: 15.5,
    protein_g: 0.7,
  },
  {
    name: "jalebi",
    Breakfast: 0,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 0,
    LactoseIntolerant: 0,
    Thyroid: 0,
    VegNonVeg: 0,
    Category: "Dessert",
    calories: 278.9,
    serving_size_g: 100,
    fat_total_g: 6.4,
    fat_saturated_g: 3.8,
    cholesterol_mg: 15,
    sodium_mg: 8,
    carbohydrates_total_g: 52.6,
    fiber_g: 0.7,
    sugar_g: 34.3,
    protein_g: 2.3,
  },
  {
    name: "banana chips",
    Breakfast: 0,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 0,
    LactoseIntolerant: 1,
    Thyroid: 0,
    VegNonVeg: 0,
    Category: "healthy fats",
    calories: 262.45,
    serving_size_g: 50,
    fat_total_g: 17.1,
    fat_saturated_g: 14.6,
    cholesterol_mg: 0,
    sodium_mg: 2.5,
    carbohydrates_total_g: 28.7,
    fiber_g: 3.85,
    sugar_g: 17.65,
    protein_g: 1.5,
  },
  {
    name: "kiwi",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 1,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "fruit",
    calories: 59.5,
    serving_size_g: 100,
    fat_total_g: 0.5,
    fat_saturated_g: 0,
    cholesterol_mg: 0,
    sodium_mg: 3,
    carbohydrates_total_g: 14.9,
    fiber_g: 3,
    sugar_g: 9.1,
    protein_g: 1.1,
  },
  {
    name: "prawns",
    Breakfast: 0,
    Lunch: 1,
    Dinner: 0,
    Diabetes: 1,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 1,
    Category: "non-veg protein",
    calories: 122,
    serving_size_g: 100,
    fat_total_g: 1.8,
    fat_saturated_g: 0.6,
    cholesterol_mg: 208,
    sodium_mg: 932,
    carbohydrates_total_g: 1.6,
    fiber_g: 0,
    sugar_g: 0,
    protein_g: 22.7,
  },
  {
    name: "apples",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 1,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "fruit",
    calories: 53.4,
    serving_size_g: 100,
    fat_total_g: 0.2,
    fat_saturated_g: 0,
    cholesterol_mg: 0,
    sodium_mg: 1,
    carbohydrates_total_g: 13.8,
    fiber_g: 2.4,
    sugar_g: 10.3,
    protein_g: 0.3,
  },
  {
    name: "brown rice",
    Breakfast: 0,
    Lunch: 1,
    Dinner: 0,
    Diabetes: 0,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "grains",
    calories: 110,
    serving_size_g: 100,
    fat_total_g: 0.8,
    fat_saturated_g: 0.2,
    cholesterol_mg: 0,
    sodium_mg: 0,
    carbohydrates_total_g: 23.1,
    fiber_g: 1.8,
    sugar_g: 0,
    protein_g: 2.3,
  },
  {
    name: "tomato rice",
    Breakfast: 0,
    Lunch: 1,
    Dinner: 0,
    Diabetes: 0,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "grains",
    calories: 97.5,
    serving_size_g: 100,
    fat_total_g: 3.1,
    fat_saturated_g: 0.2,
    cholesterol_mg: 0,
    sodium_mg: 7,
    carbohydrates_total_g: 16,
    fiber_g: 1,
    sugar_g: 1.5,
    protein_g: 1.8,
  },
  {
    name: "sweet potatoes",
    Breakfast: 1,
    Lunch: 1,
    Dinner: 0,
    Diabetes: 0,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "vegetable",
    calories: 75.9,
    serving_size_g: 100,
    fat_total_g: 0.1,
    fat_saturated_g: 0,
    cholesterol_mg: 0,
    sodium_mg: 27,
    carbohydrates_total_g: 17.6,
    fiber_g: 2.5,
    sugar_g: 5.8,
    protein_g: 1.4,
  },
  {
    name: "onion",
    Breakfast: 1,
    Lunch: 1,
    Dinner: 1,
    Diabetes: 1,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "vegetable",
    calories: 44.7,
    serving_size_g: 100,
    fat_total_g: 0.2,
    fat_saturated_g: 0,
    cholesterol_mg: 0,
    sodium_mg: 2,
    carbohydrates_total_g: 10.1,
    fiber_g: 1.4,
    sugar_g: 4.7,
    protein_g: 1.4,
  },
  {
    name: "gulab jamun",
    Breakfast: 0,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 0,
    LactoseIntolerant: 0,
    Thyroid: 0,
    VegNonVeg: 0,
    Category: "Dessert",
    calories: 293.7,
    serving_size_g: 100,
    fat_total_g: 14.6,
    fat_saturated_g: 3.1,
    cholesterol_mg: 11,
    sodium_mg: 88,
    carbohydrates_total_g: 39.7,
    fiber_g: 0.1,
    sugar_g: 35.9,
    protein_g: 3.9,
  },
  {
    name: "orange",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 0,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "fruit",
    calories: 50.4,
    serving_size_g: 100,
    fat_total_g: 0.1,
    fat_saturated_g: 0,
    cholesterol_mg: 0,
    sodium_mg: 1,
    carbohydrates_total_g: 12.4,
    fiber_g: 2.2,
    sugar_g: 8.4,
    protein_g: 0.9,
  },
  {
    name: "corn",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 0,
    LactoseIntolerant: 1,
    Thyroid: 0,
    VegNonVeg: 0,
    Category: "grains",
    calories: 93.9,
    serving_size_g: 100,
    fat_total_g: 1.5,
    fat_saturated_g: 0.2,
    cholesterol_mg: 0,
    sodium_mg: 1,
    carbohydrates_total_g: 21,
    fiber_g: 2.4,
    sugar_g: 4.6,
    protein_g: 3.4,
  },
  {
    name: "strawberry",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 0,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "fruit",
    calories: 31.9,
    serving_size_g: 100,
    fat_total_g: 0.3,
    fat_saturated_g: 0,
    cholesterol_mg: 0,
    sodium_mg: 0,
    carbohydrates_total_g: 7.7,
    fiber_g: 2,
    sugar_g: 4.9,
    protein_g: 0.7,
  },
  {
    name: "almonds",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 1,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "protein",
    calories: 301.85,
    serving_size_g: 50,
    fat_total_g: 26.35,
    fat_saturated_g: 1.95,
    cholesterol_mg: 0,
    sodium_mg: 245,
    carbohydrates_total_g: 21.3,
    fiber_g: 5.5,
    sugar_g: 2.3,
    protein_g: 10.5,
  },
  {
    name: "white rice",
    Breakfast: 0,
    Lunch: 1,
    Dinner: 1,
    Diabetes: 0,
    LactoseIntolerant: 1,
    Thyroid: 0,
    VegNonVeg: 0,
    Category: "grains",
    calories: 132,
    serving_size_g: 100,
    fat_total_g: 0.3,
    fat_saturated_g: 0.1,
    cholesterol_mg: 0,
    sodium_mg: 0,
    carbohydrates_total_g: 28.5,
    fiber_g: 0.4,
    sugar_g: 0.1,
    protein_g: 2.7,
  },
  {
    name: "mushrooms",
    Breakfast: 0,
    Lunch: 1,
    Dinner: 1,
    Diabetes: 1,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "vegetable",
    calories: 27.9,
    serving_size_g: 100,
    fat_total_g: 0.5,
    fat_saturated_g: 0.1,
    cholesterol_mg: 0,
    sodium_mg: 1,
    carbohydrates_total_g: 5.2,
    fiber_g: 2.2,
    sugar_g: 2.3,
    protein_g: 2.2,
  },
  {
    name: "sauce",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 1,
    LactoseIntolerant: 1,
    Thyroid: 0,
    VegNonVeg: 0,
    Category: "chutney",
    calories: 48.8,
    serving_size_g: 100,
    fat_total_g: 1.6,
    fat_saturated_g: 0.2,
    cholesterol_mg: 2,
    sodium_mg: 438,
    carbohydrates_total_g: 7.5,
    fiber_g: 1.8,
    sugar_g: 5,
    protein_g: 1.4,
  },
  {
    name: "chicken sausage",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 0,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 1,
    Category: "non-veg protein",
    calories: 197.4,
    serving_size_g: 100,
    fat_total_g: 10.6,
    fat_saturated_g: 2.2,
    cholesterol_mg: 91,
    sodium_mg: 665,
    carbohydrates_total_g: 0,
    fiber_g: 0,
    sugar_g: 0,
    protein_g: 24.1,
  },
  {
    name: "bananas",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 0,
    LactoseIntolerant: 1,
    Thyroid: 0,
    VegNonVeg: 0,
    Category: "fruit",
    calories: 87.4,
    serving_size_g: 100,
    fat_total_g: 0.3,
    fat_saturated_g: 0.1,
    cholesterol_mg: 0,
    sodium_mg: 1,
    carbohydrates_total_g: 22.4,
    fiber_g: 2.6,
    sugar_g: 12.2,
    protein_g: 1.1,
  },
  {
    name: "dal makhani",
    Breakfast: 0,
    Lunch: 1,
    Dinner: 1,
    Diabetes: 0,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "protein",
    calories: 170.9,
    serving_size_g: 100,
    fat_total_g: 9.6,
    fat_saturated_g: 5,
    cholesterol_mg: 22,
    sodium_mg: 189,
    carbohydrates_total_g: 15.8,
    fiber_g: 5.3,
    sugar_g: 2.4,
    protein_g: 6.4,
  },
  {
    name: "chocolate milk",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 0,
    LactoseIntolerant: 0,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "Dairy",
    calories: 81.7,
    serving_size_g: 100,
    fat_total_g: 3.4,
    fat_saturated_g: 2.1,
    cholesterol_mg: 11,
    sodium_mg: 60,
    carbohydrates_total_g: 10.5,
    fiber_g: 0.8,
    sugar_g: 9.5,
    protein_g: 3.2,
  },
  {
    name: "bread",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 0,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "bread",
    calories: 261.6,
    serving_size_g: 100,
    fat_total_g: 3.4,
    fat_saturated_g: 0.7,
    cholesterol_mg: 0,
    sodium_mg: 495,
    carbohydrates_total_g: 50.2,
    fiber_g: 2.7,
    sugar_g: 5.7,
    protein_g: 8.8,
  },
  {
    name: "coffee",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 0,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "beverages",
    calories: 1,
    serving_size_g: 100,
    fat_total_g: 0,
    fat_saturated_g: 0,
    cholesterol_mg: 0,
    sodium_mg: 1,
    carbohydrates_total_g: 0,
    fiber_g: 0,
    sugar_g: 0,
    protein_g: 0.1,
  },
  {
    name: "cheese",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 0,
    LactoseIntolerant: 0,
    Thyroid: 0,
    VegNonVeg: 0,
    Category: "Dairy",
    calories: 196.95,
    serving_size_g: 50,
    fat_total_g: 16.5,
    fat_saturated_g: 9.45,
    cholesterol_mg: 50,
    sodium_mg: 330.5,
    carbohydrates_total_g: 1.6,
    fiber_g: 0,
    sugar_g: 0.25,
    protein_g: 1.35,
  },
  {
    name: "chicken",
    Breakfast: 0,
    Lunch: 1,
    Dinner: 1,
    Diabetes: 1,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 1,
    Category: "non-veg protein",
    calories: 222.6,
    serving_size_g: 100,
    fat_total_g: 12.9,
    fat_saturated_g: 3.7,
    cholesterol_mg: 92,
    sodium_mg: 72,
    carbohydrates_total_g: 0,
    fiber_g: 0,
    sugar_g: 0,
    protein_g: 23.7,
  },
  {
    name: "mixed veg",
    Breakfast: 1,
    Lunch: 1,
    Dinner: 1,
    Diabetes: 1,
    LactoseIntolerant: 1,
    Thyroid: 0,
    VegNonVeg: 0,
    Category: "vegetable",
    calories: 31.7,
    serving_size_g: 100,
    fat_total_g: 0.3,
    fat_saturated_g: 0.1,
    cholesterol_mg: 0,
    sodium_mg: 30,
    carbohydrates_total_g: 7,
    fiber_g: 3,
    sugar_g: 2.6,
    protein_g: 1.7,
  },
  {
    name: "kebab",
    Breakfast: 0,
    Lunch: 1,
    Dinner: 1,
    Diabetes: 0,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 1,
    Category: "non-veg protein",
    calories: 110.6,
    serving_size_g: 100,
    fat_total_g: 1.1,
    fat_saturated_g: 0.3,
    cholesterol_mg: 18,
    sodium_mg: 373,
    carbohydrates_total_g: 17.4,
    fiber_g: 1.1,
    sugar_g: 13.1,
    protein_g: 7.4,
  },
  {
    name: "orange juice",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 0,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "beverages",
    calories: 46.4,
    serving_size_g: 100,
    fat_total_g: 0.1,
    fat_saturated_g: 0,
    cholesterol_mg: 0,
    sodium_mg: 1,
    carbohydrates_total_g: 11.2,
    fiber_g: 0.3,
    sugar_g: 8.3,
    protein_g: 0.7,
  },
  {
    name: "chocolate",
    Breakfast: 1,
    Lunch: 1,
    Dinner: 1,
    Diabetes: 0,
    LactoseIntolerant: 1,
    Thyroid: 0,
    VegNonVeg: 0,
    Category: "Dairy",
    calories: 270.1,
    serving_size_g: 50,
    fat_total_g: 14.7,
    fat_saturated_g: 9.3,
    cholesterol_mg: 11.5,
    sodium_mg: 39,
    carbohydrates_total_g: 29.45,
    fiber_g: 1.7,
    sugar_g: 25.7,
    protein_g: 3.9,
  },
  {
    name: "kheer",
    Breakfast: 1,
    Lunch: 1,
    Dinner: 1,
    Diabetes: 0,
    LactoseIntolerant: 0,
    Thyroid: 0,
    VegNonVeg: 0,
    Category: "Dessert",
    calories: 115.2,
    serving_size_g: 100,
    fat_total_g: 4.7,
    fat_saturated_g: 1.9,
    cholesterol_mg: 8,
    sodium_mg: 37,
    carbohydrates_total_g: 15.1,
    fiber_g: 0.3,
    sugar_g: 11.2,
    protein_g: 3.7,
  },
  {
    name: "chai",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 0,
    LactoseIntolerant: 0,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "beverages",
    calories: 2,
    serving_size_g: 100,
    fat_total_g: 0,
    fat_saturated_g: 0,
    cholesterol_mg: 0,
    sodium_mg: 0,
    carbohydrates_total_g: 0.6,
    fiber_g: 0.1,
    sugar_g: 0,
    protein_g: 0,
  },
  {
    name: "cauliflower",
    Breakfast: 1,
    Lunch: 1,
    Dinner: 1,
    Diabetes: 1,
    LactoseIntolerant: 1,
    Thyroid: 0,
    VegNonVeg: 0,
    Category: "vegetable",
    calories: 22.4,
    serving_size_g: 100,
    fat_total_g: 0.5,
    fat_saturated_g: 0.1,
    cholesterol_mg: 0,
    sodium_mg: 14,
    carbohydrates_total_g: 4.1,
    fiber_g: 2.3,
    sugar_g: 2.1,
    protein_g: 1.8,
  },
  {
    name: "mango chutney",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 0,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "chutney",
    calories: 192.6,
    serving_size_g: 100,
    fat_total_g: 0.6,
    fat_saturated_g: 0.1,
    cholesterol_mg: 0,
    sodium_mg: 42,
    carbohydrates_total_g: 48.9,
    fiber_g: 1.2,
    sugar_g: 46.3,
    protein_g: 0.8,
  },
  {
    name: "vanilla ice cream",
    Breakfast: 0,
    Lunch: 1,
    Dinner: 1,
    Diabetes: 0,
    LactoseIntolerant: 0,
    Thyroid: 0,
    VegNonVeg: 0,
    Category: "Dessert",
    calories: 208.2,
    serving_size_g: 100,
    fat_total_g: 11,
    fat_saturated_g: 6.8,
    cholesterol_mg: 44,
    sodium_mg: 80,
    carbohydrates_total_g: 23.3,
    fiber_g: 0.7,
    sugar_g: 21.4,
    protein_g: 3.5,
  },
  {
    name: "chicken pizza",
    Breakfast: 0,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 0,
    LactoseIntolerant: 1,
    Thyroid: 0,
    VegNonVeg: 1,
    Category: "non-veg protein",
    calories: 257.1,
    serving_size_g: 100,
    fat_total_g: 9.1,
    fat_saturated_g: 4,
    cholesterol_mg: 26,
    sodium_mg: 528,
    carbohydrates_total_g: 29.5,
    fiber_g: 2,
    sugar_g: 3.2,
    protein_g: 13.6,
  },
  {
    name: "cheese pizza",
    Breakfast: 0,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 0,
    LactoseIntolerant: 0,
    Thyroid: 0,
    VegNonVeg: 0,
    Category: "protein",
    calories: 259.6,
    serving_size_g: 100,
    fat_total_g: 9.6,
    fat_saturated_g: 4.5,
    cholesterol_mg: 17,
    sodium_mg: 596,
    carbohydrates_total_g: 32.9,
    fiber_g: 2.3,
    sugar_g: 3.6,
    protein_g: 11.4,
  },
  {
    name: "apple juice",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 0,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "beverages",
    calories: 46.7,
    serving_size_g: 100,
    fat_total_g: 0.1,
    fat_saturated_g: 0,
    cholesterol_mg: 0,
    sodium_mg: 3,
    carbohydrates_total_g: 11.2,
    fiber_g: 0.2,
    sugar_g: 9.6,
    protein_g: 0.1,
  },
  {
    name: "cranberry juice",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 0,
    LactoseIntolerant: 1,
    Thyroid: 0,
    VegNonVeg: 0,
    Category: "beverages",
    calories: 43.7,
    serving_size_g: 100,
    fat_total_g: 0.1,
    fat_saturated_g: 0,
    cholesterol_mg: 0,
    sodium_mg: 6,
    carbohydrates_total_g: 11,
    fiber_g: 0.1,
    sugar_g: 9.9,
    protein_g: 0.3,
  },
  {
    name: "lemon juice",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 1,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "beverages",
    calories: 16.5,
    serving_size_g: 100,
    fat_total_g: 0,
    fat_saturated_g: 0,
    cholesterol_mg: 0,
    sodium_mg: 23,
    carbohydrates_total_g: 5.5,
    fiber_g: 0.8,
    sugar_g: 1.6,
    protein_g: 0.4,
  },
  {
    name: "tomato juice",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 0,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "beverages",
    calories: 17.3,
    serving_size_g: 100,
    fat_total_g: 0.3,
    fat_saturated_g: 0,
    cholesterol_mg: 0,
    sodium_mg: 250,
    carbohydrates_total_g: 3.5,
    fiber_g: 0.4,
    sugar_g: 2.6,
    protein_g: 0.9,
  },
  {
    name: "milkshake",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 0,
    LactoseIntolerant: 0,
    Thyroid: 0,
    VegNonVeg: 0,
    Category: "beverages",
    calories: 120.4,
    serving_size_g: 100,
    fat_total_g: 2.7,
    fat_saturated_g: 1.7,
    cholesterol_mg: 11,
    sodium_mg: 109,
    carbohydrates_total_g: 21.4,
    fiber_g: 0.3,
    sugar_g: 20.7,
    protein_g: 3,
  },
  {
    name: "chicken soup",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 1,
    LactoseIntolerant: 1,
    Thyroid: 0,
    VegNonVeg: 1,
    Category: "soup",
    calories: 33.2,
    serving_size_g: 100,
    fat_total_g: 0.7,
    fat_saturated_g: 0.1,
    cholesterol_mg: 2,
    sodium_mg: 230,
    carbohydrates_total_g: 4.6,
    fiber_g: 0.9,
    sugar_g: 1,
    protein_g: 2,
  },
  {
    name: "mango",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 0,
    LactoseIntolerant: 1,
    Thyroid: 1,
    VegNonVeg: 0,
    Category: "fruit",
    calories: 61.6,
    serving_size_g: 100,
    fat_total_g: 0.4,
    fat_saturated_g: 0.1,
    cholesterol_mg: 0,
    sodium_mg: 0,
    carbohydrates_total_g: 14.8,
    fiber_g: 1.6,
    sugar_g: 13.6,
    protein_g: 0.8,
  },
  {
    name: "chicken salad",
    Breakfast: 1,
    Lunch: 0,
    Dinner: 0,
    Diabetes: 1,
    LactoseIntolerant: 1,
    Thyroid: 0,
    VegNonVeg: 1,
    Category: "salad",
    calories: 231.4,
    serving_size_g: 100,
    fat_total_g: 15.9,
    fat_saturated_g: 3.6,
    cholesterol_mg: 56,
    sodium_mg: 202,
    carbohydrates_total_g: 2.9,
    fiber_g: 0.3,
    sugar_g: 2.2,
    protein_g: 17.1,
  },
];
